apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq
  namespace: azure-iot-operations
spec:
  endpointType: mqtt
  authentication:
    method: ServiceAccountToken
    serviceAccountTokenSettings:
      audience: aio-mq
  mqttSettings:
    host: "aio-mq-dmqtt-frontend:8883"
    tls:
      mode: Enabled
      # NOTE this is where we put the server cert configmap value
      trustedCaCertificateConfigMapRef: aio-ca-trust-bundle-test-only
 