apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: my-dataflow-profile
spec:
  instanceCount: 1
  diagnostics:
    logFormat: text
    logLevel: info
    metrics:
      mode: enabled
      cacheTimeoutSeconds: 600
      exportIntervalSeconds: 10
      prometheusPort: 9600
      updateIntervalSeconds: 30
    traces:
      mode: enabled
      cacheSizeMegabytes: 16
      exportIntervalSeconds: 10
      openTelemetryCollectorAddress: null
      selfTracing:
        mode: enabled
        frequencySeconds: 30
      spanChannelCapacity: 100