apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: eventhub
  namespace: azure-iot-operations
spec:
  profileRef: profile
  operations:
    - operationType: source
      name: mq
      sourceSettings:
        endpointRef: mq
        dataSources:
          - azure-iot-operations/data/#
    - operationType: destination
      name: jomaioeh
      destinationSettings:
        endpointRef: eventhub
        dataDestination: destinationtopic