apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: eventhub
  namespace: azure-iot-operations
spec:
  endpointType: kafka
  authentication:
    method: SystemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings: 
      audience: https://jomaioeh.servicebus.windows.net
  kafkaSettings:
    host: jomaioeh.servicebus.windows.net:9093
    tls:
      mode: Enabled
