apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: eventhubendpoint
spec:
  endpointType: kafka
  authentication:
    method: systemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings: 
      audience: https://jomaioeh.servicebus.windows.net
  kafkaSettings:
    host: jomaioeh.servicebus.windows.net:9093
    tls:
      mode: Enabled
    consumerGroupId: mqConnector
