apiVersion: mq.iotoperations.azure.com/v1beta1
kind: KafkaConnectorTopicMap
metadata:
  name: fridge1
  namespace: azure-iot-operations
spec:
  kafkaConnectorRef: ehconnector
#  compression: snappy
  batching:
    enabled: true
    latencyMs: 200
    maxMessages: 100
    maxBytes: 1024
  partitionStrategy: property
  partitionKeyProperty: device-id
  copyMqttProperties: true
  routes:
    # Subscribe from MQTT topic "thermostat" and send to Kafka topic "receiving-event-hub"
    - mqttToKafka:
        name: "prosys-route1"
        mqttTopic: azure-iot-operations/data/fridge1
        kafkaTopic: receiving-prosys
        kafkaAcks: one
        qos: 1
        sharedSubscription:
          groupName: group1
          groupMinimumShareNumber: 3
    # Pull from kafka topic "sending-event-hub" and publish to MQTT topic "thermostat-commands"
    - kafkaToMqtt:
        name: "prosys-route2"
        consumerGroupId: mqConnector
        kafkaTopic: sending-prosys
        mqttTopic: azure-iot-operations/data/fridge1-commands
        qos: 0