apiVersion: mq.iotoperations.azure.com/v1beta1
kind: KafkaConnectorTopicMap
metadata:
  name: fridge6
  namespace: azure-iot-operations
spec:
  kafkaConnectorRef: ehconnector
#  compression: snappy
  batching:
    enabled: true
    latencyMs: 200
    maxMessages: 100
    maxBytes: 1024
  partitionStrategy: property
  partitionKeyProperty: device-id
  copyMqttProperties: true
  routes:
    # Subscribe from MQTT topic "fridge6" and send to Kafka topic "receiving"
    - mqttToKafka:
        name: "route11"
        mqttTopic: azure-iot-operations/data/fridge6
        kafkaTopic: receiving
        kafkaAcks: one
        qos: 1
        sharedSubscription:
          groupName: group1
          groupMinimumShareNumber: 3
    # Pull from kafka topic "sending" and publish to MQTT topic "fridge6-commands"
    - kafkaToMqtt:
        name: "route12"
        consumerGroupId: mqConnector
        kafkaTopic: sending
        mqttTopic: azure-iot-operations/data/fridge6-commands
        qos: 0