apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: eventgrid
  namespace: azure-iot-operations
spec:
  profileRef: eventgrid
  mode: enabled
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq
        dataSources:
          - azure-iot-operations/data/#
    - operationType: destination
      destinationSettings:
        endpointRef: eventgrid
        dataDestination: telemetry/fridges