apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: eventgrid
  namespace: azure-iot-operations
spec:
  profileRef: profile
  mode: enabled
  operations:
    - operationType: source
      name: mq
      sourceSettings:
        endpointRef: mq
        dataSources:
          - azure-iot-operations/data/#
        serializationFormat: Json
    - operationType: destination
      name: jomaioeh
      destinationSettings:
        endpointRef: eventgrid
        dataDestination: destinationtopic