apiVersion: mq.iotoperations.azure.com/v1beta1
kind: DataLakeConnectorTopicMap
metadata:
  name: datalake-topicmap
  namespace: azure-iot-operations
spec:
  dataLakeConnectorRef: "datalakeconnector"
  mapping:
    allowedLatencySecs: 5
    messagePayloadType: "json"
    maxMessagesPerBatch: 10
    clientId: "tempclient"
    mqttSourceTopic: "azure-iot-operations/data/opc-ua-connector-0/thermostat"
    qos: 1
    table:
      tableName: "thermostat"
      schema:
      - name: "temperatureTime"
        format: timestamp
        optional: true
        mapping: "Payload.temperature.SourceTimestamp"
      - name: "temperatureValue"
        format: int32
        optional: true
        mapping: "Payload.temperature.Value"
      - name: "Tag10Time"
        format: timestamp
        optional: true
        mapping: "Payload.Tag 10.SourceTimestamp"
      - name: "Tag10Value"
        format: int32
        optional: true
        mapping: "Payload.Tag 10.Value"
      - name: "clientId"
        format: utf8
        optional: true
        mapping: "$client_id"
      - name: "mqttTopic"
        format: utf8
        optional: true
        mapping: "$topic"
      - name: "timestamp"
        format: timestamp
        optional: true
        mapping: "$received_time"